### ISSUE TITLE
Integrate Laspy

### ISSUE THREAD

**Issue by daavoo** [daavoo/pyntcloud#133]
https://github.com/laspy/laspy

- [ ] TEST
- [x] read_las
- [ ] write_las

**Comment by zwnk** [comment]
when you want to access the header information the call crashes with:

```
cloud = PyntCloud.from_file(LasFile)
cloud.las_header.offset
```

> Traceback (most recent call last):
  File "pyncl.py", line 24, in <module>
    print(cloud.las_header.offset)
  File "C:\Users\USER\AppData\Local\Continuum\miniconda3\envs\pyntcloud\lib\site-packages\laspy\header.py", line 1135, in get_offset
    ["x_offset", "y_offset", "z_offset"]])
  File "C:\Users\USER\AppData\Local\Continuum\miniconda3\envs\pyntcloud\lib\site-packages\laspy\header.py", line 1134, in <listcomp>
    return([self.reader.get_header_property(x) for x in
  File "C:\Users\USER\AppData\Local\Continuum\miniconda3\envs\pyntcloud\lib\site-packages\laspy\base.py", line 742, in get_header_property
    val = self._get_datum(0, spec)
  File "C:\Users\USER\AppData\Local\Continuum\miniconda3\envs\pyntcloud\lib\site-packages\laspy\base.py", line 708, in _get_datum
    data = self._get_raw_datum(rec_offs, spec)
  File "C:\Users\USER\AppData\Local\Continuum\miniconda3\envs\pyntcloud\lib\site-packages\laspy\base.py", line 703, in _get_raw_datum
    return(self.data_provider._mmap[(rec_offs + spec.offs):(rec_offs + spec.offs
AttributeError: 'NoneType' object has no attribute '_mmap'

**Comment by daavoo** [comment]
Thanks for pointing that out @zwnk . I'll try to find some time to re-focus on laspy integration
