### ISSUE TITLE
Bug found in "PyntCloud.from_file()" function.

### ISSUE THREAD

**Issue by fangqiaohu** [daavoo/pyntcloud#221]
**Describe the bug**
Hi daavoo, thanks for your code!!
I use function `PyntCloud.from_file()` to read an `.obj` file, here is the bug I found.
While I use code below:
```
from pyntcloud import PyntCloud
obj = PyntCloud.from_file('my_mesh.obj')
print(obj)
```
Here is part of my `.obj` file:
```
......
v 0.000000 -0.600000 0.500000
v -0.600000 -0.600000 0.500000
f 1 26 25
f 8 4 27
f 4 28 27
f 18 1 25
f 2 6 5
f 5 3 4
......
```
An error said:
```
Traceback (most recent call last):
  File "C:/PythonProject/myimg2mesh/TEST1.py", line 207, in <module>
    obj = PyntCloud.from_file('my_mesh.obj')
  File "C:\Users\hufangqiao\Anaconda3\envs\my_img2mesh_env\lib\site-packages\pyntcloud\core_class.py", line 128, in from_file
    return cls(**FROM[ext](filename, **kwargs))
  File "C:\Users\hufangqiao\Anaconda3\envs\my_img2mesh_env\lib\site-packages\pyntcloud\io\obj.py", line 75, in read_obj
    mesh = pd.DataFrame([re.split(r'\D+', x) for x in f], dtype='i4', columns=mesh_columns)
  File "C:\Users\hufangqiao\Anaconda3\envs\my_img2mesh_env\lib\site-packages\pandas\core\frame.py", line 387, in __init__
    arrays, columns = _to_arrays(data, columns, dtype=dtype)
  File "C:\Users\hufangqiao\Anaconda3\envs\my_img2mesh_env\lib\site-packages\pandas\core\frame.py", line 7475, in _to_arrays
    dtype=dtype)
  File "C:\Users\hufangqiao\Anaconda3\envs\my_img2mesh_env\lib\site-packages\pandas\core\frame.py", line 7554, in _list_to_arrays
    coerce_float=coerce_float)
  File "C:\Users\hufangqiao\Anaconda3\envs\my_img2mesh_env\lib\site-packages\pandas\core\frame.py", line 7612, in _convert_object_array
    con=len(content)))
AssertionError: 5 columns passed, passed data had 3 columns
```
BUT!!, after I modified my `.obj` file like this, i.e. bring 'f 2 6 5' to the first line of faces:
```
......
v 0.000000 -0.600000 0.500000
v -0.600000 -0.600000 0.500000
f 2 6 5
f 1 26 25
f 8 4 27
f 4 28 27
f 18 1 25
f 5 3 4
......
```
It works.
Is this normal? Thank you!

**Comment by daavoo** [comment]
Hola @fangqiaohu ! Could you share the full .obj file?

**Comment by fangqiaohu** [comment]
Thanks, daavoo!
Here is the 2 meshes, `my_mesh_can_work.obj` and `my_mesh_cannot_work.obj`, the only difference between them, is that I bring line 49 ('f 2 6 5') to line 45 (the first line of faces). 
I think it may occur like this, if the 3 numbers in the first line of faces are all one-digit, then it's ok, but if at least one number in the first line is double-digit or sth else, then the error is to occur.
[my_mesh.zip](https://github.com/daavoo/pyntcloud/files/2489805/my_mesh.zip)

**Comment by daavoo** [comment]
@fangqiaohu thanks for pointing out the bug. it should now work as intended
