### ISSUE TITLE
Bug found in "PyntCloud.from_file()" function.

### ISSUE THREAD

**Issue by Arnoldnuo** [daavoo/pyntcloud#226]
**Describe the bug**
Hi daavoo, thanks for your code!!
I use function PyntCloud.from_file() to read an .obj file, here is the bug I found.
While I use code below:
```
from pyntcloud import PyntCloud
obj = PyntCloud.from_file('my_mesh.obj')
print(obj)
```
An error said:
```
Traceback (most recent call last):
  File "rotate.py", line 7, in <module>
    cloud = PyntCloud.from_file(file1)
  File "/Users/linuo/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pyntcloud/core_class.py", line 128, in from_file
    return cls(**FROM[ext](filename, **kwargs))
  File "/Users/linuo/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pyntcloud/io/obj.py", line 39, in read_obj
    points = pd.DataFrame(v, dtype='f4', columns=['x', 'y', 'z'])
  File "/Users/linuo/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pandas/core/frame.py", line 369, in __init__
    arrays, columns = _to_arrays(data, columns, dtype=dtype)
  File "/Users/linuo/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pandas/core/frame.py", line 6284, in _to_arrays
    dtype=dtype)
  File "/Users/linuo/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pandas/core/frame.py", line 6363, in _list_to_arrays
    coerce_float=coerce_float)
  File "/Users/linuo/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pandas/core/frame.py", line 6420, in _convert_object_array
    'columns' % (len(columns), len(content)))
AssertionError: 3 columns passed, passed data had 4 columns
```

Here is my obj file:
[mycube.zip](https://github.com/daavoo/pyntcloud/files/2555861/mycube.zip)

**Comment by CristobalBL** [comment]
Hello, 

I have the same issue. I think my .obj file have an extra column in the vertex (v) rows. 

Example of my .obj files: 

```
g -1,1,-1
v -0.225 -0.725 -1.423384 1.0
v -0.2343448 -0.725 -1.425 1.0
v -0.225 -0.7596747 -1.425 1.0
v -0.21823 -0.775 -1.425 1.0
v -0.175 -0.775 -1.420216 1.0
v -0.175 -0.725 -1.415397 1.0
v -0.125 -0.725 -1.406886 1.0
v -0.125 -0.775 -1.413693 1.0
v -0.075 -0.725 -1.401072 1.0
v -0.075 -0.775 -1.401728 1.0
```

**Comment by daavoo** [comment]
Hola @Arnoldnuo @CristobalBL . Thanks for the report. There is a problem with PyntCloud not properly handling the `w` (https://en.wikipedia.org/wiki/Wavefront_.obj_file#Geometric_vertex). I'm working on that although I have no idea about what `w` does.
