### ISSUE TITLE
pyntcloud import error

### ISSUE THREAD

**Issue by JoonHyup** [daavoo/pyntcloud#268]
Hello!
I got an error when I type 'from pyntcloud import PyntCloud' as below
Please help me how to solve it.

OS : Ubuntu Linux 16.04
Python : 3.5.2

>>> from pyntcloud import PyntCloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyntcloud/__init__.py", line 1, in <module>
    from .core_class import PyntCloud
  File "/usr/local/lib/python3.5/dist-packages/pyntcloud/core_class.py", line 8, in <module>
    from .io import FROM_FILE, TO_FILE, FROM_INSTANCE, TO_INSTANCE
  File "/usr/local/lib/python3.5/dist-packages/pyntcloud/io/__init__.py", line 1, in <module>
    from pyntcloud.io.open3d import from_open3d, to_open3d
  File "/usr/local/lib/python3.5/dist-packages/pyntcloud/io/open3d.py", line 13
    raise TypeError(f"Type {type(o3d_data)} not supported for conversion."
                                                                         ^
SyntaxError: invalid syntax

**Comment by daavoo** [comment]
Hola @JoonHyup !
pyntcloud currently requires a Python version >= 3.6.

The error is not realling telling so I would try to add an explicit exception for the Python version requirement.

**Comment by soulslicer** [comment]
is there a version of pyntcloud that supports 3.5?
