### ISSUE TITLE
Syntax Error Python 3.5

### ISSUE THREAD

**Issue by christianbrugger** [daavoo/pyntcloud#282]
The current version of pyntcloud does not work with python 3.5, although it says on the website that pyntcloud supports this python version.

I get the following error:
```
Traceback (most recent call last):
    import pyntcloud.io.ply
  File "env/lib/python3.5/site-packages/pyntcloud/__init__.py", line 1, in <module>
    from .core_class import PyntCloud
  File "env/lib/python3.5/site-packages/pyntcloud/core_class.py", line 8, in <module>
    from .io import FROM_FILE, TO_FILE, FROM_INSTANCE, TO_INSTANCE
  File "env/lib/python3.5/site-packages/pyntcloud/io/__init__.py", line 1, in <module>
    from pyntcloud.io.open3d import from_open3d, to_open3d
  File "env/lib/python3.5/site-packages/pyntcloud/io/open3d.py", line 13
    raise TypeError(f"Type {type(o3d_data)} not supported for conversion."
                    ^
SyntaxError: invalid syntax
```

F-strings are not supported in Python 3.5, so this does not compile. Remvoing the `f` makes everything work.

 - OS: Ubuntu 16.04
 - pyntcloud-0.1.2 (via pip)

**Comment by daavoo** [comment]
Hola @christianbrugger! Sorry for the confusion, the minimum required Python version is 3.6. I have updated the setup.py accordingly and will update the documentation and release.
