### ISSUE TITLE
SciPy issue while using pip install

### ISSUE THREAD

**Issue by OloOcki** [daavoo/pyntcloud#283]
Dear Community of pyntcloud,

I really enjoyed working with pyntcloud! I have made some testing within conda, Python 3.6 and everything worked perfectly.

Now, I would like to integrate pyntcloud to a software called FME. FME installs all the stuff via pip and uses Python 3.7 but cannot import the pyntcloud package somehow (i.e. some xml Python parser works). When I try to run it the following error occurs: 

###
` ```
   2020-06-30 15:43:16|   0.5|  0.0|INFORM|Using Python interpreter from `C:\Program Files\FME\fmepython37\python37.dll' with PYTHONHOME `C:\Program Files\FME\fmepython37'
    2020-06-30 15:43:16|   0.5|  0.0|INFORM|Python version 3.7 loaded successfully
    2020-06-30 15:43:16|   0.5|  0.0|INFORM|Adding folder `C:\Users\SAVe\AppData\Local\Temp\' to the python path
    2020-06-30 15:43:16|   0.5|  0.0|INFORM|Emptying factory pipeline
    2020-06-30 15:43:17|   1.3|  0.8|ERROR |Python Exception <OSError>: [WinError 126] The specified module could not be found
    2020-06-30 15:43:17|   1.3|  0.0|ERROR |Error executing string `import<space>fme<lf>import<space>fmeobjects<lf><lf>import<space>pyntcloud<lf><lf>def<space>processFeature<openparen>feature<closeparen>:<lf><space><space><space><space>pass<lf><lf>'
    2020-06-30 15:43:17|   1.3|  0.0|FATAL |Factory proxy not initialized
    2020-06-30 15:43:17|   1.3|  0.0|FATAL |PythonCaller (PythonFactory): PythonFactory failed to process feature
    2020-06-30 15:43:17|   1.3|  0.0|ERROR |A fatal error has occurred. Check the logfile above for details
````

Trying to look under the hood and with help of @fhildin from FME Forum the SciPy library seems to cause the problem:

` ```
   Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\mywindowsaccount\Documents\FME\Plugins\Python\pyntcloud\__init__.py", line 1, in <module>
        from .core_class import PyntCloud
      File "C:\Users\mywindowsaccount\Documents\FME\Plugins\Python\pyntcloud\core_class.py", line 6, in <module>
        from .structures.base import StructuresDict
      File "C:\Users\mywindowsaccount\Documents\FME\Plugins\Python\pyntcloud\structures\__init__.py", line 4, in <module>
        from .convex_hull import ConvexHull
      File "C:\Users\mywindowsaccount\Documents\FME\Plugins\Python\pyntcloud\structures\convex_hull.py", line 2, in <module>
        from scipy.spatial import ConvexHull as scipy_ConvexHull
      File "C:\Users\mywindowsaccount\Documents\FME\Plugins\Python\scipy\__init__.py", line 104, in <module>
        from . import _distributor_init
      File "C:\Users\mywindowsaccount\Documents\FME\Plugins\Python\scipy\_distributor_init.py", line 61, in <module>
        WinDLL(os.path.abspath(filename))
      File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 364, in __init__
    OSError: [WinError 126] The specified module could not be found
````

Do you know guys how to solve it? How to import pyntcloud properly? I guess that it is not a problem related to FME but rather to pyntcloud.

**Comment by daavoo** [comment]
Hola @OloOcki Could you share with me some details about how to replicate the installation enviroment where you are finding the issue?

**Comment by OloOcki** [comment]
Hi,
Actually the problem is solved - it was on the FME side.
Please find the solution [here ](https://community.safe.com/s/question/0D54Q000080hdLQSAY/python-external-package-installation-problem).

**Comment by daavoo** [comment]
> Hi,
> Actually the problem is solved - it was on the FME side.
> Please find the solution [here ](https://community.safe.com/s/question/0D54Q000080hdLQSAY/python-external-package-installation-problem).

Glad to hear that! Thanks for linking the solution
